# The Basics of R

In [ ]:
#Examples of R things
3+4
6+12


In [2]:
# Arithmetics
# Addition
5 + 5

# Subtraction
5 - 5

# Multiplication
5 * 5

# Division
5 / 5

# Exponential
5 ^ 5

# Modulo 
28 %% 6 

[1] 10

[1] 0

[1] 25

[1] 1

[1] 3125

[1] 4

In [3]:
# Variable assignment and printing

# Assign the value 42 to x
x <- 42

# Print out the value of the variable x
print(x)

[1] 42


In [4]:
my_numeric <- 42.5
my_integer <- 7
my_character <- "some text"
my_logical <- TRUE

In [5]:
class(my_numeric)
class(my_integer)
class(my_character)
class(my_logical)

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "logical"

In [6]:
# show defined variables
ls()

[1] "my_character" "my_integer"   "my_logical"   "my_numeric"   "x"

In [7]:
# Casting and type checking
# Create variables var1, var2 and var3
var1 <- TRUE
var2 <- 0.3
var3 <- "i"

# var1 is logical; convert it to character: var1_char
var1_char = as.character(var1)

# See whether var1_char is a character
is.character(var1_char)

# var2 is numeric; convert it to logical: var2_log
var2_log = as.logical(var2)

# Inspect the class of var2_log
class(var2_log)

# var3 is character; convert it to numeric: var3_num
# fails
var3_num = as.numeric(var3)

[1] TRUE

[1] "logical"

Warning message in eval(expr, envir, enclos):
"NAs introduzidos por coerção"

In [1]:
# these are vectors!
numeric_vector <- c(1, 10, 49)
character_vector <- c("a", "b", "c")
boolean_vector <- c(TRUE, FALSE, TRUE)

In [6]:
# selection by comparisson
c(4,5,6) > 5
# kinda like dataframes in python?

# exactly like it actually:
numeric_vector <- c(1, 10, 49)
larger_than_ten <- numeric_vector > 10
numeric_vector[larger_than_ten]

# bigger example
numeric_vector2 <- c(1, 10, 49, 25, 37, 9, 19)
larger_than_ten2 <- numeric_vector2 > 10
numeric_vector2[larger_than_ten2]

[1] FALSE FALSE  TRUE

[1] 49

[1] 49 25 37 19

In [11]:
# the : operator?!
help(":")

Colon                   package:base                   R Documentation

_C_o_l_o_n _O_p_e_r_a_t_o_r

_D_e_s_c_r_i_p_t_i_o_n:

     Generate regular sequences.

_U_s_a_g_e:

     from:to
        a:b
     
_A_r_g_u_m_e_n_t_s:

    from: starting value of sequence.

      to: (maximal) end value of the sequence.

    a, b: 'factor's of the same length.

_D_e_t_a_i_l_s:

     The binary operator ':' has two meanings: for factors 'a:b' is
     equivalent to 'interaction(a, b)' (but the levels are ordered and
     labelled differently).

     For other arguments 'from:to' is equivalent to 'seq(from, to)',
     and generates a sequence from 'from' to 'to' in steps of '1' or
     '-1'.  Value 'to' will be included if it differs from 'from' by an
     integer up to a numeric fuzz of about '1e-7'.  Non-numeric
     arguments are coerced internally (hence without dispatching
     methods) to numeric-complex values will have their imaginary parts
     discarded with a warning.

_V_a_l_u_e:

     For numeric arguments, a numeric vector.  This will be of type
     'integer' if 'from' is integer-valued and the result is
     representable in the R integer type, otherwise of type '"double"'
     (aka 'mode' '"numeric"').

     For factors, an unordered factor with levels labelled as 'la:lb'
     and ordered lexicographically (that is, 'lb' varies fastest).

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.
     (for numeric arguments: S does not have ':' for factors.)

_S_e_e _A_l_s_o:

     'seq' (a _generalization_ of 'from:to').

     As an alternative to using ':' for factors, 'interaction'.

     For ':' used in the formal representation of an interaction, see
     'formula'.

_E_x_a_m_p_l_e_s:

     1:4
     pi:6 # real
     6:pi # integer
     
     f1 <- gl(2, 3); f1
     f2 <- gl(3, 2); f2
     f1:f2 # a factor, the "cross"  f1 x f2

In [8]:
# let's create matrices, why aren't they called MULTI DIMMENSIONAL VECTORS??
matrix(1:9, byrow = TRUE, nrow = 3, ncol = 3)
matrix(1:9, byrow = TRUE, nrow = 2, ncol = 5)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

Warning message in matrix(1:9, byrow = TRUE, nrow = 2, ncol = 5):
"comprimento dos dados [9] não é um submúltiplo ou múltiplo do número de linhas [2]"

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4    5   
[2,] 6    7    8    9    1

In [12]:
# exercise requires matrix to use byrow=TRUE, why?
# byrow logical. 
# If FALSE (the default) the matrix is filled by columns, otherwise the matrix is filled by rows
help("matrix")

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'matrix' creates a matrix from the given set of values.

     'as.matrix' attempts to turn its argument into a matrix.

     'is.matrix' tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or 'expression'
          vector).  Non-atomic classed R objects are coerced by
          'as.vector' and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If 'FALSE' (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A 'dimnames' attribute for the matrix: 'NULL' or a 'list' of
          length 2 giving the row and column names respectively.  An
          empty list is treated as 'NULL', and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than 'NULL') 'rownames'.  The default,
          'NA', uses 'NULL' rownames if the data frame has 'automatic'
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of 'nrow' or 'ncol' is not given, an attempt is made to
     infer it from the length of 'data' and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in 'data' to fill the matrix, then
     the elements in 'data' are recycled.  If 'data' has length zero,
     'NA' of an appropriate type is used for atomic vectors ('0' for
     raw vectors) and 'NULL' for lists.

     'is.matrix' returns 'TRUE' if 'x' is a vector and has a '"dim"'
     attribute of length 2 and 'FALSE' otherwise.  Note that a
     'data.frame' is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     'as.matrix' is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying 'as.vector' to
     factors and 'format' to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for 'as.matrix' calls 'as.vector(x)', and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     'is.matrix' is a primitive function.

     The 'print' method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form 'integer,7' indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like
     
       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)

     will avoid duplicating 'x'.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     'data.matrix', which attempts to convert to a numeric matrix.

     A matrix is the special case of a two-dimensional 'array'.

_E_x_a

In [13]:
# using the function factor
# a vector called student_status
student_status <- c("student", "not student", "student", "not student")

# turn student_status into a factor and save it in the variable categorical_student
categorical_student <- factor(student_status )

# print categorical_student to the console
print(categorical_student)

[1] student     not student student     not student
Levels: not student student


In [17]:
# we have dataframes
print(mtcars)

                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0   

In [18]:
# not fun like python objects tho
# print the first 6 rows of mtcars
head(mtcars,6)

# print the structure of mtcars
tail(mtcars,6)

# print the dimensions of mtcars
dim(mtcars)

# print structure of dataframe
str(mtcars)

colnames(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

mpg  cyl disp  hp  drat wt    qsec vs am gear carb
Porsche 914-2  26.0 4   120.3  91 4.43 2.140 16.7 0  1  5    2   
Lotus Europa   30.4 4    95.1 113 3.77 1.513 16.9 1  1  5    2   
Ford Pantera L 15.8 8   351.0 264 4.22 3.170 14.5 0  1  5    4   
Ferrari Dino   19.7 6   145.0 175 3.62 2.770 15.5 0  1  5    6   
Maserati Bora  15.0 8   301.0 335 3.54 3.570 14.6 0  1  5    8   
Volvo 142E     21.4 4   121.0 109 4.11 2.780 18.6 1  1  4    2

[1] 32 11

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


[1] "mpg"  "cyl"  "disp" "hp"   "drat" "wt"   "qsec" "vs"   "am"   "gear"
[11] "carb"

In [20]:
# creating a dataframe from a bunch of series

planets <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

planet_df = data.frame(planets, type, diameter, rotation, rings)

colnames(planet_df)

planet_df

[1] "planets"  "type"     "diameter" "rotation" "rings"

planets type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
8 Neptune Gas giant           3.883      0.67   TRUE

In [21]:
# select the values in the first row and second and third columns
planet_df[1, c(2,3)]

# select the entire third column
planet_df$diameter

type               diameter
1 Terrestrial planet 0.382

[1]  0.382  0.949  1.000  0.532 11.209  9.449  4.007  3.883

In [22]:
my_vector <- 1:10 
my_matrix <- matrix(1:9, ncol = 3)
my_df <- mtcars[1:10,]
my_list <- list(my_vector, my_matrix, my_df)

# lists, like vectors, but with any sort of data
print(my_list)

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4



In [30]:
#second elemnt
my_list[2]

#first columns from third component
my_list[[3]]$mpg

[[1]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2